# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
        - feat
    - title: Bug Fixes 🐛
      labels:
        - Semver-Patch
        - bug
        - fix
    - title: Documentation 📚
      labels:
        - doc
    - title: Testing 🧪
      labels:
        - test
    - title: Other Changes
      labels:
        - "*"
