# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - 'feat:'
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
