name: release executable file

on:
  push:
    tags:
      - v*
permissions:
  contents: write
  packages: write

jobs:
  release-windows-amd64:
    name: release-windows-amd64
    strategy:
      matrix:
        os:
          - windows
        #          - linux
        arch:
          - amd64
    #          - arm64
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generated content
        uses: yuk1ty/conventional-release-note@v1.1.1
        id: gen_note
        with:
          kind: default
          tag-pattern: v*
          current-tag: ${{ github.ref_name }}

      - name: Create a new release note
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.gen_note.outputs.summary }}
          draft: false
          prerelease: false

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
