name: release executable file

on:
  push:
    tags:
      - 'v*'


permissions:
  contents: write
  packages: write

jobs:
  release-windows-amd64:
    name: release-windows-amd64
    strategy:
      matrix:
        os:
          - windows
        #          - linux
        arch:
          - amd64
    #          - arm64
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
