name: Generate Release Note

on:
  push:

jobs:
  generate-release-note:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Note
        id: generate-note
        uses: ./.github/actions/generate-release-note
        with:
          release_note_file: 'release_note.txt'

      - name: Print Release Note
        run: cat release_note.txt
